config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :whos
  
  root 'games#new'
end

app/models/doing.rb
class Doing < ActiveRecord::Base
  belongs_to :game
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :who
  has_one :doing
  has_one :see
  has_one :when
  has_one :where
  has_one :with
end

app/models/see.rb
class See < ActiveRecord::Base
  belongs_to :game
end

app/models/when.rb
class When < ActiveRecord::Base
  belongs_to :game
end

app/models/where.rb
class Where < ActiveRecord::Base
  belongs_to :game
end

app/models/who.rb
class Who < ActiveRecord::Base
  belongs_to :game
end

app/models/with.rb
class With < ActiveRecord::Base
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
    done?
  end
  
  def new
  end
  
  def create
    @game = Game.new(game_params)
    
    respond_to do |format|
      if @game.save
        format.html { redirect_to new_who_path(:game_id => @game.id) }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def index
  end
  
  def done?
    @game = Game.find(params[:id])
    return @game.doing.present? && @game.see.present? && @game.when.present? &&
           @game.where.present? && @game.who.present? && @game.with.present?
  end
  
  def next
    @game = Game.find(params[:id])
    @game.done?
  end
  
  private
  def game_params
    params.require(:game).permit()
  end
end

app/controllers/whos_controller.rb
class WhosController < ApplicationController
  def show
    @who = Who.find(params[:id])
  end
  
  def new
    @who = Who.new
    @game = params[:game_id]
  end
  
  def create
    @who = Who.new(who_params)
    @game = @who.game
    @who.save
    redirect_to @game
  end
  
  def get_game
    Game.where(:id => params["game_id"])
  end
  
  private
  def who_params
    params.require(:who).permit(:email, :text, :game_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/whos_helper.rb
module WhosHelper
end

app/views/games/new.html.erb
<%= form_for :game, url: games_path do |f| %>
  <p>
   	<%= f.label :email %><br>
   	<%= f.text_field :email %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/games/show.html.erb
<p>Who: <%= @game.who.text %></p>
<p>With whom: <%= @game.who.text %></p>
<p>Doing what: <%= @game.who.text %></p>
<p>Where: <%= @game.who.text %></p>
<p>When: <%= @game.who.text %></p>
<p>Who saw: <%= @game.who.text %></p>

Who, with who, doing what, where, when, who see it

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fivew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/whos/new.html.erb
<%= form_for :who, url: whos_path do |f| %>
<%= f.hidden_field :game_id, :value => @game.to_i %>
<% puts "XXXXXXXXxxxxxxxXXXXXXXXxxxxxxxXXXXXXXXxxxxxxxXXXXXXXXxxxxxxx"%>
<% puts @game %>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= params %>

app/views/whos/show.html.erb
<%= @who.game %>